# Generated by Django 4.2.30 on 2026-10-05 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('duration_minutes', models.PositiveIntegerField(default=90, verbose_name='Длительность, минут')),
            ],
            options={
                'verbose_name': 'контест',
                'verbose_name_plural': 'контесты',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Имя участника')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин контеста')),
                ('password_hash', models.CharField(editable=False, max_length=256)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.contest', verbose_name='Контест')),
            ],
            options={
                'verbose_name': 'участник контеста',
                'verbose_name_plural': 'участники контеста',
                'ordering': ['contest', 'login'],
            },
        ),
        migrations.CreateModel(
            name='ContestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Номер')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('statement', models.TextField(verbose_name='Условие (HTML)')),
                ('time_limit', models.FloatField(default=2.0, verbose_name='Лимит времени на один тест, сек')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.contest', verbose_name='Контест')),
            ],
            options={
                'verbose_name': 'задача контеста',
                'verbose_name_plural': 'задачи контеста',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('plan', models.CharField(blank=True, choices=[('start', 'Старт'), ('mentor', 'Ментор')], max_length=10, verbose_name='Пакет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Номер')),
                ('input_data', models.TextField(blank=True, verbose_name='Входные данные')),
                ('expected_output', models.TextField(verbose_name='Правильный ответ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.contesttask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++')], max_length=10, verbose_name='Язык')),
                ('code', models.TextField(verbose_name='Код')),
                ('verdict', models.CharField(choices=[('PENDING', 'Проверяется'), ('OK', 'Принято'), ('WA', 'Неверный ответ'), ('TLE', 'Превышено время'), ('RE', 'Ошибка выполнения'), ('CE', 'Ошибка компиляции')], default='PENDING', max_length=8, verbose_name='Вердикт')),
                ('passed', models.PositiveSmallIntegerField(default=0, verbose_name='Пройдено тестов')),
                ('total', models.PositiveSmallIntegerField(default=0, verbose_name='Всего тестов')),
                ('marks', models.CharField(blank=True, max_length=500, verbose_name='Результат по тестам')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.contestaccount', verbose_name='Участник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.contesttask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'отправка',
                'verbose_name_plural': 'отправки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Адрес (латиницей)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, help_text='Можно использовать теги: h2, h3, p, ul, ol, table, pre, code, div class="note".', verbose_name='Содержимое (HTML)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать ученикам')),
                ('parent', models.ForeignKey(blank=True, help_text='Оставьте пустым, если это самостоятельная тема.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.section', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'раздел материалов',
                'verbose_name_plural': 'материалы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Ученик'), ('assistant', 'Помощник')], max_length=10, verbose_name='Кто')),
                ('content', models.TextField(verbose_name='Текст')),
                ('archived', models.BooleanField(default=False, help_text='Ученик нажал «Новый диалог»: помощник эту переписку уже не учитывает, но куратор её видит.', verbose_name='Диалог завершён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_messages', to='core.section', verbose_name='Раздел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'сообщение помощника',
                'verbose_name_plural': 'диалоги с помощником',
                'ordering': ['id'],
            },
        ),
    ]
