# Generated by Django 4.2.30 on 2026-10-07 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kazakh_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENTSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('subject', models.SlugField(default='informatics', verbose_name='Предмет')),
                ('title', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('title_kk', models.CharField(blank=True, max_length=200, verbose_name='Название (KZ)')),
                ('source_url', models.URLField(blank=True, verbose_name='Спецификация RU')),
                ('source_url_kk', models.URLField(blank=True, verbose_name='Спецификация KZ')),
                ('question_count', models.PositiveSmallIntegerField(default=40)),
                ('max_score', models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                'verbose_name': 'спецификация ЕНТ',
                'verbose_name_plural': 'спецификации ЕНТ',
                'ordering': ['-year', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='ENTTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Код темы')),
                ('title', models.CharField(max_length=300, verbose_name='Название (RU)')),
                ('title_kk', models.CharField(blank=True, max_length=300, verbose_name='Название (KZ)')),
                ('mapping_notes', models.TextField(blank=True, verbose_name='Примечания к покрытию')),
                ('sections', models.ManyToManyField(blank=True, help_text='Начальное сопоставление может покрывать только часть официальной темы.', limit_choices_to={'parent__isnull': True}, related_name='ent_topics', to='core.section', verbose_name='Корневые темы BYTE')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.entspecification')),
            ],
            options={
                'verbose_name': 'тема ЕНТ',
                'verbose_name_plural': 'темы ЕНТ',
                'ordering': ['specification', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='entspecification',
            constraint=models.UniqueConstraint(fields=('year', 'subject'), name='ent_spec_year_subject_unique'),
        ),
        migrations.AddConstraint(
            model_name='enttopic',
            constraint=models.UniqueConstraint(fields=('specification', 'code'), name='ent_topic_spec_code_unique'),
        ),
    ]
