# Generated by Django 4.2.30 on 2026-10-09 07:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_seed_ent_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestaccount',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Назначается куратором. Совпадение имени или логина не подтверждает владельца.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Ученик BYTE'),
        ),
        migrations.AddField(
            model_name='contesttask',
            name='ent_topics',
            field=models.ManyToManyField(blank=True, related_name='contest_tasks', to='core.enttopic', verbose_name='Темы ЕНТ'),
        ),
        migrations.AddField(
            model_name='entspecification',
            name='forecast_weight_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Основание весов (RU)'),
        ),
        migrations.AddField(
            model_name='entspecification',
            name='forecast_weight_note_kk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Основание весов (KZ)'),
        ),
        migrations.AddField(
            model_name='enttopic',
            name='forecast_weight',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Модельное допущение, не официальные баллы. По умолчанию все темы равновесны.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Относительный вес в прогнозе'),
        ),
        migrations.CreateModel(
            name='ENTPracticeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Набранные баллы')),
                ('max_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум баллов')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата прохождения')),
                ('source', models.CharField(max_length=200, verbose_name='Вариант / источник')),
                ('reference', models.CharField(help_text='Например mock:variant-12:user-42:attempt-1; защищает от повторного импорта.', max_length=200, unique=True, verbose_name='Уникальный ID результата')),
                ('verified', models.BooleanField(default=False, verbose_name='Результат проверен')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_results', to='core.entspecification', verbose_name='Спецификация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ent_practice_results', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'результат пробника ЕНТ',
                'verbose_name_plural': 'результаты пробников ЕНТ',
                'ordering': ['-taken_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='entpracticeresult',
            constraint=models.CheckConstraint(check=models.Q(('max_score__gt', 0)), name='ent_practice_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='entpracticeresult',
            constraint=models.CheckConstraint(check=models.Q(('score__lte', models.F('max_score'))), name='ent_practice_score_valid'),
        ),
    ]
