# Generated by Django 4.2.30 on 2026-10-09 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contestaccount_user_contesttask_ent_topics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('authors', models.CharField(max_length=500, verbose_name='Авторы')),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Класс')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақша')], max_length=2, verbose_name='Язык')),
                ('publisher', models.CharField(max_length=200, verbose_name='Издательство')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('edition', models.CharField(blank=True, max_length=100, verbose_name='Издание')),
                ('isbn', models.CharField(max_length=32, unique=True, verbose_name='ISBN')),
                ('page_count', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать рекомендации')),
            ],
            options={
                'verbose_name': 'учебник',
                'verbose_name_plural': 'учебники',
                'ordering': ['grade', 'title', 'year'],
            },
        ),
        migrations.CreateModel(
            name='TextbookReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=30, verbose_name='Параграф')),
                ('title', models.CharField(max_length=250, verbose_name='Название в учебнике')),
                ('page_start', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Печатная страница начала')),
                ('pdf_page', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Страница PDF')),
                ('verified', models.BooleanField(default=False, verbose_name='Ссылка проверена')),
                ('verification_note', models.TextField(blank=True, verbose_name='Основание проверки')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова RU/KZ через запятую')),
                ('ent_topics', models.ManyToManyField(blank=True, related_name='textbook_references', to='core.enttopic', verbose_name='Темы ЕНТ')),
                ('sections', models.ManyToManyField(blank=True, related_name='textbook_references', to='core.section', verbose_name='Разделы BYTE')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.textbook', verbose_name='Учебник')),
            ],
            options={
                'verbose_name': 'ссылка на параграф',
                'verbose_name_plural': 'ссылки на параграфы',
                'ordering': ['textbook_id', 'page_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='textbookreference',
            constraint=models.UniqueConstraint(fields=('textbook', 'paragraph'), name='unique_textbook_paragraph'),
        ),
    ]
